// Voice-over: one edge-tts call per sentence, silence-trimmed, measured, then
// laid onto the timeline. Writes (paths for the default film; see film.mjs):
//   build/vo/<key>.mp3           raw synth
//   build/timeline.json / .js    shot + sentence timings (source of truth downstream)
//   build/vo.wav                 sentences placed at their timeline start (mono 48k)
//   script.md                    the script with timings
//   pyre-launch-captions.srt     sentence captions
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { ROOT, BUILD, FILM, OUT, script } from "./film.mjs";
import { SR, writeWav, decode } from "./wav.mjs";

const { SENTENCES, VOICE, RATE, layout, PICTURE } = await script();
const VO = join(BUILD, "vo");
const SCRIPT_MD = FILM === "launch" ? "script.md" : `script-${FILM}.md`;
const SCRIPT_SRC = FILM === "launch" ? "src/script.mjs" : `src/script-${FILM}.mjs`;

const srtTime = (s) => {
  const ms = Math.round(s * 1000);
  const h = Math.floor(ms / 3600000), m = Math.floor((ms % 3600000) / 60000), sec = Math.floor((ms % 60000) / 1000), r = ms % 1000;
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(sec).padStart(2, "0")},${String(r).padStart(3, "0")}`;
};
const clock = (s) => `${String(Math.floor(s / 60)).padStart(2, "0")}:${(s % 60).toFixed(1).padStart(4, "0")}`;

export function synth({ force = false } = {}) {
  mkdirSync(VO, { recursive: true });
  const durations = {};
  const pcm = {};
  for (const s of SENTENCES) {
    // cache key includes the spoken text + voice, so an edited line re-synthesises and an unchanged one does not
    const mp3 = join(VO, `${s.key}-${createHash("sha1").update(`${VOICE}|${RATE}|${s.say}`).digest("hex").slice(0, 8)}.mp3`);
    if (force || !existsSync(mp3)) {
      execFileSync("python", ["-m", "edge_tts", "--voice", VOICE, `--rate=${RATE}`, "--text", s.say, "--write-media", mp3], { stdio: "inherit" });
    }
    const samples = decode(mp3, { trim: true });
    pcm[s.key] = samples;
    durations[s.key] = +(samples.length / SR).toFixed(3);
  }
  return { durations, pcm };
}

export function buildVoice(opts) {
  const { durations, pcm } = synth(opts);
  const tl = layout(durations);
  writeFileSync(join(BUILD, "timeline.json"), JSON.stringify(tl, null, 2));
  writeFileSync(join(BUILD, "timeline.js"), `window.TIMELINE = ${JSON.stringify(tl)};\n`);

  // place sentences
  const out = new Float32Array(Math.ceil((tl.duration + 1) * SR));
  for (const s of tl.sentences) {
    const src = pcm[s.key];
    const o = Math.round(s.start * SR);
    for (let i = 0; i < src.length; i++) out[o + i] += src[i];
  }
  writeWav(join(BUILD, "vo.wav"), [out]);

  // captions
  const srt = tl.sentences.map((s, i) => `${i + 1}\n${srtTime(s.start)} --> ${srtTime(s.end)}\n${s.text}\n`).join("\n");
  writeFileSync(join(ROOT, `${OUT}-captions.srt`), srt + "\n");

  // script.md
  const words = SENTENCES.reduce((a, s) => a + s.text.split(/\s+/).length, 0);
  const lines = [
    `# ${OUT} — voice-over script`,
    "",
    `Voice: edge-tts \`${VOICE}\` (rate ${RATE}). ${words} words · ${tl.duration.toFixed(1)} s picture. Generated by \`src/voice.mjs\` from \`${SCRIPT_SRC}\`; timings are the measured audio placed on the timeline (\`build/${FILM === "launch" ? "" : FILM + "/"}timeline.json\`).`,
    "",
    "| in | out | beat | shot | line |",
    "|---|---|---|---|---|",
  ];
  for (const s of tl.sentences) lines.push(`| ${clock(s.start)} | ${clock(s.end)} | ${s.beat} | ${s.shot} | ${s.text} |`);
  lines.push("", "## shots", "", "| in | dur | shot | picture |", "|---|---|---|---|");
  for (const s of tl.shots) lines.push(`| ${clock(s.start)} | ${s.dur.toFixed(1)}s | ${s.id} | ${PICTURE[s.id] ?? ""} |`);
  lines.push("", "## spoken forms", "", "Where the caption and the spoken text differ (numbers, tickers), the spoken form is:", "");
  for (const s of SENTENCES) if (s.say !== s.text) lines.push(`- “${s.text}” → *${s.say}*`);
  lines.push("");
  writeFileSync(join(ROOT, SCRIPT_MD), lines.join("\n"));
  console.log(`[voice] ${tl.sentences.length} sentences, picture ${tl.duration.toFixed(2)}s`);
  return tl;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  buildVoice({ force: process.argv.includes("--force") });
}
