// Voice-over: one edge-tts call per sentence, silence-trimmed, measured, then
// laid onto the timeline. Writes:
//   build/vo/<key>.mp3           raw synth
//   build/timeline.json / .js    shot + sentence timings (source of truth downstream)
//   build/vo.wav                 sentences placed at their timeline start (mono 48k)
//   script.md                    the script with timings
//   pyre-launch-captions.srt     sentence captions
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { BEATS, SENTENCES, VOICE, RATE, layout } from "./script.mjs";
import { SR, writeWav, decode } from "./wav.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const BUILD = join(ROOT, "build");
const VO = join(BUILD, "vo");

const srtTime = (s) => {
  const ms = Math.round(s * 1000);
  const h = Math.floor(ms / 3600000), m = Math.floor((ms % 3600000) / 60000), sec = Math.floor((ms % 60000) / 1000), r = ms % 1000;
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(sec).padStart(2, "0")},${String(r).padStart(3, "0")}`;
};
const clock = (s) => `${String(Math.floor(s / 60)).padStart(2, "0")}:${(s % 60).toFixed(1).padStart(4, "0")}`;

export function synth({ force = false } = {}) {
  mkdirSync(VO, { recursive: true });
  const durations = {};
  const pcm = {};
  for (const s of SENTENCES) {
    const mp3 = join(VO, `${s.key}.mp3`);
    if (force || !existsSync(mp3)) {
      execFileSync("python", ["-m", "edge_tts", "--voice", VOICE, `--rate=${RATE}`, "--text", s.say, "--write-media", mp3], { stdio: "inherit" });
    }
    const samples = decode(mp3, { trim: true });
    pcm[s.key] = samples;
    durations[s.key] = +(samples.length / SR).toFixed(3);
  }
  return { durations, pcm };
}

export function buildVoice(opts) {
  const { durations, pcm } = synth(opts);
  const tl = layout(durations);
  writeFileSync(join(BUILD, "timeline.json"), JSON.stringify(tl, null, 2));
  writeFileSync(join(BUILD, "timeline.js"), `window.TIMELINE = ${JSON.stringify(tl)};\n`);

  // place sentences
  const out = new Float32Array(Math.ceil((tl.duration + 1) * SR));
  for (const s of tl.sentences) {
    const src = pcm[s.key];
    const o = Math.round(s.start * SR);
    for (let i = 0; i < src.length; i++) out[o + i] += src[i];
  }
  writeWav(join(BUILD, "vo.wav"), [out]);

  // captions
  const srt = tl.sentences.map((s, i) => `${i + 1}\n${srtTime(s.start)} --> ${srtTime(s.end)}\n${s.text}\n`).join("\n");
  writeFileSync(join(ROOT, "pyre-launch-captions.srt"), srt + "\n");

  // script.md
  const words = SENTENCES.reduce((a, s) => a + s.text.split(/\s+/).length, 0);
  const lines = [
    "# pyre-launch — voice-over script",
    "",
    `Voice: edge-tts \`${VOICE}\` (rate ${RATE}). ${words} words · ${tl.duration.toFixed(1)} s picture. Generated by \`src/voice.mjs\` from \`src/script.mjs\`; timings are the measured audio placed on the timeline (\`build/timeline.json\`).`,
    "",
    "| in | out | beat | shot | line |",
    "|---|---|---|---|---|",
  ];
  for (const s of tl.sentences) lines.push(`| ${clock(s.start)} | ${clock(s.end)} | ${s.beat} | ${s.shot} | ${s.text} |`);
  lines.push("", "## shots", "", "| in | dur | shot | picture |", "|---|---|---|---|");
  const PICTURE = {
    open: "obsidian; “coins that *build* apps.” rises through a mask; heat lifts from the bottom edge; “revenue *burns* them.”",
    "launch-mg": "prompt box types the one sentence → spec card (what / who pays / mvp / price) → stake pill → launch line with the PONS v2 factory address",
    "launch-cap": "real capture: pyre.fun/launch hero, pointer onto the live preview card (parallax)",
    "fees-mg": "1% fee bar → 70% creator share → splits fill 60 / 25 / 15",
    "fees-cap": "real capture: coin page, “the loop” panel, pointer walks the six cells · demo data",
    "agent-mg": "console streams the build log; gate checklist lights: build · playwright · screenshots · lighthouse · reviewer → deploy",
    "app-mg": "browser frame <slug>.pyre.fun; USDG charge card; “relayed by the treasury · 0 gas · EIP-3009”",
    "revenue-mg": "revenue bar splits 85 / 10 / 5",
    "revenue-cap": "real capture: pyre.fun home feed, pointer sweeps the ranked cards · demo data",
    "burn-mg": "supply stack hollows from the top; buy → burn() → totalSupply falls; attestation calldata types out",
    "burn-cap": "real capture: pyre.fun/burns ledger, chart tilting into the table · demo data",
    "dormant-mg": "the mark cools to ash at $0 budget; a fee arrives and the heat rises again",
    proof: "408 unit tests · 58/68 production audit · 27/28 perimeter · independent security review",
    close: "lockup; pyre.fun · Robinhood Chain · @PyreFun; $PYRE launching soon · buybacks are burns, never distributions",
  };
  for (const s of tl.shots) lines.push(`| ${clock(s.start)} | ${s.dur.toFixed(1)}s | ${s.id} | ${PICTURE[s.id] ?? ""} |`);
  lines.push("", "## spoken forms", "", "Where the caption and the spoken text differ (numbers, tickers), the spoken form is:", "");
  for (const s of SENTENCES) if (s.say !== s.text) lines.push(`- “${s.text}” → *${s.say}*`);
  lines.push("");
  writeFileSync(join(ROOT, "script.md"), lines.join("\n"));
  console.log(`[voice] ${tl.sentences.length} sentences, picture ${tl.duration.toFixed(2)}s`);
  return tl;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  buildVoice({ force: process.argv.includes("--force") });
}
